# Generated by Django 2.2.5 on 2020-02-19 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='artwork1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.ImageField(blank=True, upload_to='artworks')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artapp.UserProfileInfo')),
            ],
        ),
    ]
