# Generated by Django 2.2.5 on 2020-02-19 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artapp', '0002_artwork1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork1',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
