# Generated by Django 2.2.5 on 2020-02-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artapp', '0003_auto_20200219_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork1',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
