# Generated by Django 2.2.5 on 2020-02-19 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artapp', '0004_artwork1_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork1',
            old_name='description',
            new_name='desc',
        ),
    ]
