# Generated by Django 2.2.5 on 2020-02-20 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artapp', '0007_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='more',
            name='about',
        ),
        migrations.RemoveField(
            model_name='more',
            name='age',
        ),
    ]
