# Generated by Django 2.2.5 on 2020-02-20 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artapp', '0008_auto_20200220_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='more',
            name='user1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
