# Generated by Django 2.2.5 on 2020-02-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artapp', '0009_auto_20200220_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='more',
            name='ppic',
            field=models.ImageField(upload_to='profile_pics'),
        ),
    ]
