# Generated by Django 2.2.5 on 2020-02-22 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artapp', '0010_auto_20200220_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='more',
            name='ppic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
        migrations.CreateModel(
            name='more1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverphoto', models.ImageField(blank=True, upload_to='cover_pics')),
                ('user1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
