# Generated by Django 2.2.5 on 2020-02-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artapp', '0013_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='age',
            field=models.IntegerField(),
        ),
    ]
