# Generated by Django 2.2.5 on 2020-02-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artapp', '0014_auto_20200222_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='Dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
