# Generated by Django 2.2.5 on 2020-02-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artapp', '0015_auto_20200222_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='links',
            field=models.URLField(blank=True),
        ),
    ]
