# Generated by Django 2.2.5 on 2020-02-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artapp', '0016_details_links'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='links',
            new_name='link',
        ),
        migrations.AddField(
            model_name='details',
            name='link1',
            field=models.URLField(blank=True),
        ),
    ]
