# Generated by Django 2.2.5 on 2020-02-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artapp', '0017_auto_20200223_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork1',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
